# JOYENT LDAP KIT 					  Configuration Makefile 
################################################################################

KIT_ROOT=	`pwd`
HOST=		`hostname`
DATE=		`date +%m.%d.%y-%H:%M:%S`

DIT_SUFFIX=	dc=ops,dc=joyent,dc.com
NISDOMAIN=	ops.joyent.com
NISDC=		ops

# Your PRIMARY LDAP server is "pref", your SECONDARY is "server"
# The name MUST match the CN in your TLS certs and be in /etc/hosts!
PREFSERVERS=	ldap1.joyent.com:636
SERVERS=	ldap2.joyent.com:636

SERVER1_HOSTENTRY=	"10.0.91.11      ldap1.joyent.com ldap1"
SERVER2_HOSTENTRY=	"10.0.91.12      ldap2.joyent.com ldap2"

# Generate passwords.coming 'apg -a 0 -m 20'
ROOTDN_PASS=		LowtEnRyesurWitwehoi
MIRROR_PASS=		jidjojneenjohunFegDo
PROXY_PASS=		giepJoytdulnednadlej

# The SSHA version of the above, can not include /'s;.come: slappasswd -s $(ROOTDN_PASS)
ROOTDN_PASS_SSHA= 	{SSHA}eLR48ahS0vim0jotfcfXfTl
MIRROR_PASS_SSHA=	{SSHA}0FuAwkQTslFNyJyKUGfFjxI
PROXY_PASS_SSHA=	{SSHA}zcBp2SlVzZBdO3YQCM6Futd

# These certs and keys should be placed in the pki/ directory
TLS_CA_CERT=	ca.crt
TLS_SRV_CERT=	server.crt
TLS_SRV_KEY=	server.key


MIRROR_PEER_IP=	10.10.10.10
